server:
  port: 9001

spring:
  application:
    name: auth-service

security:
  jwt:
    secret: "smart-exam-cloud-secret-key-must-be-at-least-32-bytes"
    expiration-seconds: 7200

management:
  endpoints:
    web:
      exposure:
        include: health,info

