server:
  port: 9001

spring:
  application:
    name: auth-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB_AUTH:3}
      timeout: 2s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

security:
  jwt:
    secret: "smart-exam-cloud-secret-key-must-be-at-least-32-bytes"
    expiration-seconds: 7200

management:
  endpoints:
    web:
      exposure:
        include: health,info
