server:
  port: 9500

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/analysis_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
  data:
    redis:
      database: 6

snowflake:
  worker-id: 5
  datacenter-id: 1
