server:
  port: 9400

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/grading_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
  data:
    redis:
      database: 5

snowflake:
  worker-id: 4
  datacenter-id: 1
