server:
  port: 9000

spring:
  application:
    name: gateway-service
  config:
    import:
      - 'optional:nacos:common.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true'
      - 'optional:nacos:${spring.application.name}.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true'
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.242.10:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR:192.168.242.10:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/v1/questions/**,/api/v1/papers/**
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/api/v1/exams/**,/api/v1/sessions/**
        - id: grading-service
          uri: lb://grading-service
          predicates:
            - Path=/api/v1/grading/**
        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/api/v1/reports/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**

security:
  jwt:
    secret: "smart-exam-cloud-secret-key-must-be-at-least-32-bytes"
    expiration-seconds: 7200

management:
  endpoints:
    web:
      exposure:
        include: health,info
