server:
  port: 9500

spring:
  application:
    name: analysis-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info

